spring:
  application:
    name: UMGC City Application
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: UMGCityHikariConnPool
      connection-timeout: 20000
      minimum-idle: 2
      maximum-pool-size: 4
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      path: /h2-console
      enabled: true

server:
  port: 5000

